### ISSUE TITLE
It says "This page is not yet translated." but pages exist

### ISSUE THREAD

**Issue by ant-tar** [modxorg/Docs#262]
## Affected page(s)

Please open https://docs.modx.com/current/en/extending-modx/xpdo/class-reference/xpdo/xpdo.addpackage#switchsettings
and after - language bar on top right corner

## What needs to be improved?

![2021-03-04 10 32 13](https://user-images.githubusercontent.com/2815640/109927469-558b4180-7cd5-11eb-9f13-56c9224117d1.png)

https://docs.modx.com/current/en/extending-modx/xpdo/class-reference/xpdo/xpdo.addpackage
https://docs.modx.com/current/ru/extending-modx/xpdo/class-reference/xpdo/xpdo.addpackage
https://docs.modx.com/3.x/ru/extending-modx/xpdo/class-reference/xpdo/xpdo.addpackage
https://docs.modx.com/3.x/en/extending-modx/xpdo/class-reference/xpdo/xpdo.addpackage

Pages are exist for both EN and RU languages and for both 2.x and 3.x versions.

But it says "This page is not yet translated." for some reason, what's wrong here?

**Comment by Ibochkarev** [comment]
@Mark-H need your help. I don't understand what the problem is.

**Comment by Mark-H** [comment]
Try adding an index.md at ru/extending-modx/xpdo/class-reference/xpdo/index.md

That was missing in en as well causing the entire subsection of methods on the xPDO class not being shown in the menu. And I think translation refs are also based on the menu generation.

**Comment by Ibochkarev** [comment]
> Try adding an index.md at ru/extending-modx/xpdo/class-reference/xpdo/index.md
> 
> That was missing in en as well causing the entire subsection of methods on the xPDO class not being shown in the menu. And I think translation refs are also based on the menu generation.

Ok! Thanks

**Comment by Ibochkarev** [comment]
@himurovich, thanks for the find. I have corrected.

**Comment by Mark-H** [comment]
Hmm, this still doesn't work does it?

**Comment by Ibochkarev** [comment]
> Hmm, this still doesn't work does it?

Everything works.

**Comment by ghost** [comment]
<img width="432" alt="Screen Shot 2021-03-04 at 13 23 30" src="https://user-images.githubusercontent.com/1073780/109956911-e15c9800-7cec-11eb-9ab1-f436fb2d8e40.png">

**Comment by ghost** [comment]
I presume that means that there are not yet Dutch or Spanish translations.

**Comment by Ibochkarev** [comment]
Yes, indeed the inscription remained, but the transitions worked.

**Comment by ghost** [comment]
Oops... I see that now.

**Comment by Mark-H** [comment]
Ahh, my bad. It's fixed in 2.x but I looked in 3.x. That'll her updated next time that's merged then.

**Comment by ghost** [comment]
Um... no, actually those two pages end up on the home page in their respective languages. So something is still not right.

**Comment by Mark-H** [comment]
There's is no Spanish or Dutch translation, that's expected. The problem was the Russian translation (which does exist) not getting linked up, which it now does in 2.x.

**Comment by ant-tar** [comment]
oo how quickly you solved everything here, thanks guys for the clarity!

**Comment by ghost** [comment]
I tend to poke at things until I understand what is going on.
